{% set version = "4.0.0" %}

package:
  name: arcsi
  version: {{ version }}

source:
  git_url: https://github.com/remotesensinginfo/arcsi.git
  git_tag: main

build:
  number: 0
  skip: True  # [win and py27]
  # Windows recipe includes .bat file copy so use bld.bat
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"  # [not win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - py6s
    - gdal
    - rsgislib >=5.0
    - rios
    - scikit-learn
    - python-fmask
    - h5py
    - lightgbm

test:
  imports:
    - arcsilib
  commands:
    - arcsi.py -h

about:
  home: https://www.arcsi.remotesensing.info
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: Software for the Atmospheric and Radiometric Correction of Satellite Imagery (ARCSI)

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
