{% set version = "4.0.4" %}

package:
  name: arcsi
  version: {{ version }}

source:
  url: https://github.com/remotesensinginfo/arcsi/archive/refs/tags/{{ version }}.tar.gz
  sha256: cbcc1b2f388e7d2ebd487639292c74f5ba1f40eec87f211f3ce8b100b1f35403

build:
  number: 1
  skip: true  # [win]
  # Windows recipe includes .bat file copy so use bld.bat
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [not win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - py6s
    - gdal
    - rsgislib >=5.0
    - rios
    - scikit-learn
    - python-fmask
    - h5py
    - lightgbm

test:
  imports:
    - arcsilib
  commands:
    - arcsi.py -h

about:
  home: https://www.arcsi.remotesensing.info
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: Software for the Atmospheric and Radiometric Correction of Satellite Imagery (ARCSI)

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
