{% set version = "3.1.6" %}

package:
  name: arcsi
  version: {{ version }}

source:
  fn: arcsi-{{ version }}.tar.gz
  url: https://bitbucket.org/petebunting/arcsi/downloads/arcsi-{{ version }}.tar.gz
  sha256: 5a53e5e9b1769c41d28e2a6644d4add68c1c922d93a882bd69fa457a47cfb5d5

build:
  number: 2
  # Windows recipe includes .bat file copy so use bld.bat
  script: python setup.py install  # [unix]
  # rsgislib not available due to mpfr only supporting vc14 and above
  skip: True  # [win and py<35]

requirements:
  host:
    - python
  run:
    - python
    - py6s
    - gdal
    - rsgislib 3.6.*
    - rios
    - scikit-learn
    - python-fmask
    - h5py

test:
  imports:
    - arcsilib
  commands:
    - arcsi.py -h

about:
  home: https://www.arcsi.remotesensing.info
  license: GPLv3
  license_file: LICENSE.txt
  summary: Software for the Atmospheric and Radiometric Correction of Satellite Imagery (ARCSI)

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
