{% set version = "4.0.5" %}

package:
  name: arcsi
  version: {{ version }}

source:
  url: https://github.com/remotesensinginfo/arcsi/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6cae28247b74f7a8758ec95e46df74e60cee44acb0f426b0dfd6500d2f7a1d57

build:
  number: 0
  skip: true  # [win]
  # Windows recipe includes .bat file copy so use bld.bat
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [not win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - py6s
    - gdal
    - rsgislib >=5.1
    - rios
    - scikit-learn
    - python-fmask
    - h5py
    - lightgbm

test:
  imports:
    - arcsilib
  commands:
    - arcsi.py -h

about:
  home: https://www.arcsi.remotesensing.info
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: Software for the Atmospheric and Radiometric Correction of Satellite Imagery (ARCSI)

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
