{% set version = "3.2.4" %}

package:
  name: arcsi
  version: {{ version }}

source:
  fn: arcsi-{{ version }}.tar.gz
  url: https://bitbucket.org/petebunting/arcsi/downloads/arcsi-{{ version }}.tar.gz
  sha256: 265aca1708d7b32e13a849dfca13208fb0fbeb9597173d804c1dfb2965bf6242

build:
  number: 1
  # Windows recipe includes .bat file copy so use bld.bat
  script: python setup.py install  # [unix]
  # rsgislib not available due to mpfr only supporting vc14 and above
  skip: True  # [(win and py<35) or (py>36)]

requirements:
  host:
    - python
  run:
    - python
    - py6s
    - gdal
    - rsgislib >= 4.0.0
    - rios
    - scikit-learn
    - python-fmask
    - h5py

test:
  imports:
    - arcsilib
  commands:
    - arcsi.py -h

about:
  home: https://www.arcsi.remotesensing.info
  license: GPLv3
  license_file: LICENSE.txt
  summary: Software for the Atmospheric and Radiometric Correction of Satellite Imagery (ARCSI)

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
