{% set version = "4.0.3" %}

package:
  name: arcsi
  version: {{ version }}

source:
  url: https://github.com/remotesensinginfo/arcsi/archive/refs/tags/{{ version }}.tar.gz
  sha256: a986681db3e2d713067f9a3a8e68fadcd5183797f423ea8f0e3ebb08965a9d03

build:
  number: 0
  skip: true  # [win]
  # Windows recipe includes .bat file copy so use bld.bat
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [not win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - py6s
    - gdal
    - rsgislib >=5.0
    - rios
    - scikit-learn
    - python-fmask
    - h5py
    - lightgbm

test:
  imports:
    - arcsilib
  commands:
    - arcsi.py -h

about:
  home: https://www.arcsi.remotesensing.info
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: Software for the Atmospheric and Radiometric Correction of Satellite Imagery (ARCSI)

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
