{% set version = "3.2.4" %}

package:
  name: arcsi
  version: {{ version }}

source:
  fn: arcsi-{{ version }}.tar.gz
  url: https://bitbucket.org/petebunting/arcsi/downloads/arcsi-{{ version }}.tar.gz
  sha256: 7d46e0d4af25d386d9e367d607fd3a8ca0a9a32830bc9039e530da5e3b582650

build:
  number: 1
  # Windows recipe includes .bat file copy so use bld.bat
  script: python setup.py install  # [unix]

requirements:
  host:
    - python
  run:
    - python
    - py6s
    - gdal
    - rsgislib >=4.0.0
    - rios
    - scikit-learn
    - python-fmask
    - h5py

test:
  imports:
    - arcsilib
  commands:
    - arcsi.py -h

about:
  home: https://www.arcsi.remotesensing.info
  license: GPLv3
  license_file: LICENSE.txt
  summary: Software for the Atmospheric and Radiometric Correction of Satellite Imagery (ARCSI)

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
