{% set version = "2.2.24" %}

package:
  name: arcsi
  version: {{ version }}

source:
  fn: arcsi-{{ version }}.tar.gz
  url: https://bitbucket.org/petebunting/arcsi/downloads/arcsi-{{ version }}.tar.gz
  sha256: d92c3023923a2e9c9235d92307a560e519095748c8e7700dc7956510f74b40fe

build:
  number: 1
  # Windows recipe includes .bat file copy so use bld.bat
  script: python setup.py install  # [unix]
  # rsgislib not available due to mpfr only supporting vc14 and above
  skip: True  # [win and py<35]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]

  run:
    - python
    - py6s
    - rsgislib 3.4.*
    - rios
    - scikit-learn
    - h5py
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]

test:
  imports:
    - arcsilib
  commands:
    - arcsi.py -h

about:
  home: http://rsgislib.org/arcsi
  license: GPLv3
  license_file: LICENSE.txt
  summary: Software for the Atmospheric and Radiometric Correction of Satellite Imagery (ARCSI)

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
