travis:
  secure:
    BINSTAR_TOKEN: VdpJ4TSrn2XNYGTyAHb1vRlwIg0XVyu4eM6NAIai5U55TvMMcIJV2sV1oErzUJR+ShYaTVwtGtQJnSOB5i1w7Rjj+vdx0TXlj9fGE3Sa/GvAHa7nzbAKa3VA+docPbulSvgHkaDnrZaJEMD5Fmvf+Gq9z5u8NKiGLDNh4urzkRBoNjDu3aMm7nxUSvKEF0V1M0pUIhHWPJcAYH8dZLh7KfT6pHd8rm6KXkZzMs1ZCgCsnEgc/5uozfQWCm9WvaRShJX5Tg0f0WbJvmnvmZL8hTI1YWWiP7S3k9ot8oxr1oTmM2vBZqmtyZZ+KlM6Kh340ButP3h32Pl03l5kipb1nVzCKgM8CT82wfWxjCHKS2ox/yMOfaPeuTzvAwXn3Xn9A0PGq8Ot0PK7lLjtTnd8bvh0RV3zPZD/MeOB/zeuRWII6sJjxeUcTeXAwZD6QDlgZwhI91I8nGe4JpzM5Y/3G+P3D02XpRJ+epd0PccHPRctt05YyYvnmLeLE9ABhuFxi89xTV/vBnmVmCpOOZc+glYWuSjhCc47xkXJEI1xtu5n0jw1uagNmF/XS3kbnoX/NkenFQRMVkzfA+9Dol8KSqUT36NuLPxzV9n2uCuSYcvbne31HQMGdY509eCu756LOX4N6Ij4By1xJ4GnvQhmFaFuFhc3JMv5ts3/tfVIZII=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: false
