travis:
  secure:
    BINSTAR_TOKEN: 537Jv6G00C1d8JySZCLZoQeytWi36t/fl1TQlcZqqvcZ2yrpK9B4wPaon1xX06Jak2Et0x1zGt0f38dKoniLUQsQIbU/nqj2ss+JyJv7OFlAygcDaQfA0Y9JnygjFggIh27QJaiuZ7FFQOcLddH7utXR8/tMvePUVjqTPZ7RWMx3r8fNRI+Q3qkm+jgFSx++Agn89/9JXXfKjk+WWmhMBFtbzwOyxqOG7IQLyMMLZzFiNbaMkRmm7yP5UlPNApdxA0j1oNp6Uk6SRQgpACIKaAA80jCHq7lny/3gwUUWXhloLnJvHAo6uAOtlw0Gz3CiG7RnE8FbfXd8HeyF2+aV9c9HcwEVYWFZXEt6tT+pkjBRvK6IGfteWG/w66MQbqIzTpn1W5j1jdS3KKflyd2oNWOodLZI/jIgKtEjbfLfPTZ6SkH0ozNeiBHw07e2zDcKeYpo1926zBqv9zUv8IWw3H5gxdtWmezpxY0XGXf5dqV2oq4Vh95KixC/bn5F4zRqRlpTh/0KyjJpJOMkgEhTNbCex4jZlZ68UFw3ZdkW9Ym9YjudblHZkrrBSPHyh2jObYR71UL8mI84kVRjV6LTqoULnJksyRn9wIZHbuzXhuOOyKe5C3dYsGdczU2kFtNJI4AfacBoJLfaRQOs00ye8AB00q+YrwvBTyBDQtkUmKY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: false
